//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dota2ModKit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dota2ModKit.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click to change current addon. Right-click for
        ///more options..
        /// </summary>
        internal static string AddonTileTooltip {
            get {
                return ResourceManager.GetString("AddonTileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to break up.
        /// </summary>
        internal static string AskToBreakUpMsg {
            get {
                return ResourceManager.GetString("AskToBreakUpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Re-Color.
        /// </summary>
        internal static string BulkRecolor {
            get {
                return ResourceManager.GetString("BulkRecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Resize:.
        /// </summary>
        internal static string BulkResize {
            get {
                return ResourceManager.GetString("BulkResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGELOG.
        /// </summary>
        internal static string CHANGELOG {
            get {
                return ResourceManager.GetString("CHANGELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiles CoffeeScript files in the panorama/scripts/coffeescript
        ///directory to JavaScript files in panorama/scripts.
        /// </summary>
        internal static string CoffeeScriptCompileBtnTooltip {
            get {
                return ResourceManager.GetString("CoffeeScriptCompileBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoffeeScript files compiled!.
        /// </summary>
        internal static string CoffeeScriptFilesCompiled {
            get {
                return ResourceManager.GetString("CoffeeScriptFilesCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine KV Files.
        /// </summary>
        internal static string CombineKVFiles {
            get {
                return ResourceManager.GetString("CombineKVFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combines KV files in the scripts/npc directory of this addon.Prompts to break up the KV files if not done so already..
        /// </summary>
        internal static string CombineKVFilesBtnTooltip {
            get {
                return ResourceManager.GetString("CombineKVFilesBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine success!.
        /// </summary>
        internal static string CombineKVSuccess {
            get {
                return ResourceManager.GetString("CombineKVSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the content directory of this addon..
        /// </summary>
        internal static string ContentTileTooltip {
            get {
                return ResourceManager.GetString("ContentTileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find required file.
        /// </summary>
        internal static string CouldntFindRequiredFile {
            get {
                return ResourceManager.GetString("CouldntFindRequiredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse ID!.
        /// </summary>
        internal static string CouldntParseID {
            get {
                return ResourceManager.GetString("CouldntParseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to customize this tile!.
        /// </summary>
        internal static string CustomTileTooltip {
            get {
                return ResourceManager.GetString("CustomTileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D2ModKit will download it now..
        /// </summary>
        internal static string D2ModKitWillDownloadItNow {
            get {
                return ResourceManager.GetString("D2ModKitWillDownloadItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t exist!.
        /// </summary>
        internal static string DirectoryDoesntExistCaption {
            get {
                return ResourceManager.GetString("DirectoryDoesntExistCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory doesn&apos;t exist.
        /// </summary>
        internal static string DirectoryDoesntExistMsg {
            get {
                return ResourceManager.GetString("DirectoryDoesntExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider a donation to the developer!.
        /// </summary>
        internal static string DonateBtnTooltip {
            get {
                return ResourceManager.GetString("DonateBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the workshop ID.
        /// </summary>
        internal static string EnterWorkshopID {
            get {
                return ResourceManager.GetString("EnterWorkshopID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Sound.Name.
        /// </summary>
        internal static string FindSoundName {
            get {
                return ResourceManager.GetString("FindSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Sound Names with a .vsnd path.
        /// </summary>
        internal static string FindSoundNameBtnTooltip {
            get {
                return ResourceManager.GetString("FindSoundNameBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for this to work. Use GCFScape to extract .vtex_c files into this folder..
        /// </summary>
        internal static string ForThisToWork_UseGCF {
            get {
                return ResourceManager.GetString("ForThisToWork_UseGCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the game directory of this addon..
        /// </summary>
        internal static string GameTileTooltip {
            get {
                return ResourceManager.GetString("GameTileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Tooltips.
        /// </summary>
        internal static string GenerateTooltips {
            get {
                return ResourceManager.GetString("GenerateTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates tooltips from the scripts/npc files of this addon,
        ///which you can easily transfer over to addon_language.txt
        ///files..
        /// </summary>
        internal static string GenerateTooltipsBtnTooltip {
            get {
                return ResourceManager.GetString("GenerateTooltipsBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a search on GitHub.com.
        /// </summary>
        internal static string GithubGoTooltip {
            get {
                return ResourceManager.GetString("GithubGoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Up KV File.
        /// </summary>
        internal static string HasNotBeenBrokenUpCaption {
            get {
                return ResourceManager.GetString("HasNotBeenBrokenUpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has not been broken up. Break it up now?.
        /// </summary>
        internal static string HasNotBeenBrokenUpMsg {
            get {
                return ResourceManager.GetString("HasNotBeenBrokenUpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyValues.
        /// </summary>
        internal static string KeyValues {
            get {
                return ResourceManager.GetString("KeyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Script.
        /// </summary>
        internal static string LuaScript {
            get {
                return ResourceManager.GetString("LuaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the numbers above with the numbers below:.
        /// </summary>
        internal static string MatchTheNumbers {
            get {
                return ResourceManager.GetString("MatchTheNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be inside the content directory of.
        /// </summary>
        internal static string MustBeInsideTheContentDirOf {
            get {
                return ResourceManager.GetString("MustBeInsideTheContentDirOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dota 2 addons detected..
        /// </summary>
        internal static string NoDota2AddonsDetectedCaption {
            get {
                return ResourceManager.GetString("NoDota2AddonsDetectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dota 2 addons detected. There must be one addon for D2ModKit to function properly. Exiting..
        /// </summary>
        internal static string NoDota2AddonsDetectedMsg {
            get {
                return ResourceManager.GetString("NoDota2AddonsDetectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sound names found..
        /// </summary>
        internal static string NoSoundNamesFound {
            get {
                return ResourceManager.GetString("NoSoundNamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text inputted!.
        /// </summary>
        internal static string NoTextInputted {
            get {
                return ResourceManager.GetString("NoTextInputted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the KV entry for this spell.
        /// </summary>
        internal static string OpensTheKVEntry {
            get {
                return ResourceManager.GetString("OpensTheKVEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Lua script for this spell.
        /// </summary>
        internal static string OpensTheLuaScript {
            get {
                return ResourceManager.GetString("OpensTheLuaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options saved!.
        /// </summary>
        internal static string OptionsSaved {
            get {
                return ResourceManager.GetString("OptionsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Options page.
        /// </summary>
        internal static string OptionsTooltip {
            get {
                return ResourceManager.GetString("OptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Designer.
        /// </summary>
        internal static string ParticleDesigner {
            get {
                return ResourceManager.GetString("ParticleDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides options to bulk modify the color and size of
        ///selected particles..
        /// </summary>
        internal static string ParticleDesignerBtnTooltip {
            get {
                return ResourceManager.GetString("ParticleDesignerBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle design failed!.
        /// </summary>
        internal static string ParticleDesignFailed {
            get {
                return ResourceManager.GetString("ParticleDesignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Files.
        /// </summary>
        internal static string ParticleFiles {
            get {
                return ResourceManager.GetString("ParticleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle selected.
        /// </summary>
        internal static string ParticleSelected {
            get {
                return ResourceManager.GetString("ParticleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particles selected.
        /// </summary>
        internal static string ParticlesSelected {
            get {
                return ResourceManager.GetString("ParticlesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particles successfully designed!.
        /// </summary>
        internal static string ParticlesSuccessfullyDesigned {
            get {
                return ResourceManager.GetString("ParticlesSuccessfullyDesigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug!.
        /// </summary>
        internal static string ReportBugTooltip {
            get {
                return ResourceManager.GetString("ReportBugTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click to edit tile..
        /// </summary>
        internal static string RightClickToEditTile {
            get {
                return ResourceManager.GetString("RightClickToEditTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Particles To Design.
        /// </summary>
        internal static string SelectParticlesToDesign {
            get {
                return ResourceManager.GetString("SelectParticlesToDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .tga Files To Compile.
        /// </summary>
        internal static string SelectTGAFilesToCompile {
            get {
                return ResourceManager.GetString("SelectTGAFilesToCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select vtex_c Files To Decompile.
        /// </summary>
        internal static string SelectVTEXCToDecompile {
            get {
                return ResourceManager.GetString("SelectVTEXCToDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size change.
        /// </summary>
        internal static string SizeChange {
            get {
                return ResourceManager.GetString("SizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpellLibrary not found.
        /// </summary>
        internal static string SpellLibNotFoundCaption {
            get {
                return ResourceManager.GetString("SpellLibNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpellLibrary.
        /// </summary>
        internal static string SpellLibrary {
            get {
                return ResourceManager.GetString("SpellLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens up a GUI browser for the Dota2 SpellLibrary project.
        /// </summary>
        internal static string SpellLibraryBtnTooltip {
            get {
                return ResourceManager.GetString("SpellLibraryBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpellLibrary will now be cloned into.
        /// </summary>
        internal static string SpellLibWillNowBeClonedMsg {
            get {
                return ResourceManager.GetString("SpellLibWillNowBeClonedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Steam Workshop page for this addon.
        /// </summary>
        internal static string SteamTileTooltip {
            get {
                return ResourceManager.GetString("SteamTileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tga files successfully compiled!.
        /// </summary>
        internal static string TGAFilesSuccessfullyCompiled {
            get {
                return ResourceManager.GetString("TGAFilesSuccessfullyCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available!.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View version changelog.
        /// </summary>
        internal static string VersionTooltip {
            get {
                return ResourceManager.GetString("VersionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Dota 2 VPK (requires GCFScape).
        /// </summary>
        internal static string VPKTooltip {
            get {
                return ResourceManager.GetString("VPKTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vtex_c files must be present in.
        /// </summary>
        internal static string VTEXCFilesMustBePresentIn {
            get {
                return ResourceManager.GetString("VTEXCFilesMustBePresentIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop ID.
        /// </summary>
        internal static string WorkshopID {
            get {
                return ResourceManager.GetString("WorkshopID", resourceCulture);
            }
        }
    }
}
